/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;

/**
 *
 * @author Pc
 */
public class VtnCrearHospital extends javax.swing.JFrame
{

    /**
     * Creates new form VtnCrearHospital
     */
    public VtnCrearHospital()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        cveHospital = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        Nivel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de hospitales");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        Aceptar.setBackground(new java.awt.Color(151, 247, 185));
        Aceptar.setText("Aceptar");

        Cancelar.setBackground(new java.awt.Color(255, 115, 115));
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CancelarActionPerformed(evt);
            }
        });

        cveHospital.setToolTipText("Clave");
        cveHospital.setEnabled(false);
        cveHospital.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cveHospitalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                cveHospitalKeyTyped(evt);
            }
        });

        Direccion.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                DireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                DireccionKeyTyped(evt);
            }
        });

        Nivel.setEnabled(false);
        Nivel.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                NivelKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                NivelKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(Cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(Aceptar)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cveHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(cveHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar)
                    .addComponent(Cancelar))
                .addGap(143, 143, 143))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CancelarActionPerformed
    {//GEN-HEADEREND:event_CancelarActionPerformed
        CtrlInterfaz.limpia(Direccion, Nivel);
        CtrlInterfaz.habilita(false, Nivel,Aceptar);
        CtrlInterfaz.selecciona(Direccion);
    }//GEN-LAST:event_CancelarActionPerformed

    private void cveHospitalKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cveHospitalKeyPressed
    {//GEN-HEADEREND:event_cveHospitalKeyPressed

    }//GEN-LAST:event_cveHospitalKeyPressed

    private void DireccionKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_DireccionKeyPressed
    {//GEN-HEADEREND:event_DireccionKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, Direccion, Nivel);
    }//GEN-LAST:event_DireccionKeyPressed

    private void NivelKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_NivelKeyPressed
    {//GEN-HEADEREND:event_NivelKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, Nivel, Aceptar);
    }//GEN-LAST:event_NivelKeyPressed

    private void cveHospitalKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cveHospitalKeyTyped
    {//GEN-HEADEREND:event_cveHospitalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cveHospitalKeyTyped

    private void DireccionKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_DireccionKeyTyped
    {//GEN-HEADEREND:event_DireccionKeyTyped
        Validaciones.validaAlfanumerico(evt, 20, Direccion.getText());
    }//GEN-LAST:event_DireccionKeyTyped

    private void NivelKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_NivelKeyTyped
    {//GEN-HEADEREND:event_NivelKeyTyped
        Validaciones.validaEntero(evt, 5, Nivel.getText());
    }//GEN-LAST:event_NivelKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        new PRINCIPAL().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnCrearHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnCrearHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnCrearHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnCrearHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnCrearHospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Nivel;
    private javax.swing.JTextField cveHospital;
    // End of variables declaration//GEN-END:variables
}
